---
name: legacy-perf

update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-180000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3468.19"

releases:
- name: routing-release
  url: routing-release
  version: create
- name: routing-perf
  url: routing-perf-release
  version: create

instance_groups:

- name: nats
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: nats
    release: nats
    properties:
      nats:
        password: "((nats_password))"
        user: nats

- name: router
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: gorouter
    release: routing
    properties:
      router:
        enable_ssl: false
        status:
          password: "((router_status_password))"
          user: router-status
        route_services_secret: "((router_route_services_secret))"
      uaa:
        clients:
          gorouter:
            secret: ""
        ssl:
          port: 0
  - name: cpumonitor
    release: routing-perf
    properties:
      per_cpu: true

- name: gostatic
  azs:
  - z1
  instances: 1
  vm_type: static
  stemcell: trusty
  networks:
  - name: default
  jobs:
  - name: gostatic
    release: routing-perf
    properties:
      gostatic:
        response_size: 1

- name: http_route_populator
  azs:
  - z1
  instances: 1
  vm_type: default
  stemcell: trusty
  networks:
  - name: default
  jobs:
  - name: http_route_populator
    release: routing-perf
    properties:
      http_route_populator:
        app_domain: perf.com
        app_name: gostatic
        num_routes: 1

- name: throughputramp
  azs:
  - z3
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: trusty
  networks:
  - name: default
  jobs:
  - name: throughputramp
    release: routing-perf
    properties:
      throughputramp:
        host: gostatic-0.perf.com
        access_key_id: "((results_bucket_aws_access_key_id))"
        secret_access_key: "((results_bucket_aws_secret_access_key))"
        bucket_name: "((results_bucket_name))"
        lower_concurrency: 1
        upper_concurrency: 60
        local_csv: "/var/vcap/sys/log"

variables:
- name: nats_password
  type: password
- name: router_status_password
  type: password
- name: router_route_services_secret
  type: password
